name: NodeJS MicroService

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '13.x'                # set this to the node version to use

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: development
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Dependencies
      run: npm install
     -run: npm run build --if-present
     -run: npm test
